#trigger
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo
  labels:
    app: demo
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|demo|demo'
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      serviceAccountName: demo
      volumes:
        - name: demo-cm
          configMap:
            name: demo-cm
      containers:
        - name: demo
          envFrom:
            - configMapRef:
                name: demo-cm
                optional: true
            - secretRef:
                name: test-secret
          image: artifactory.dentsplysirona.com/dpns-docker-local-sandbox/demo/demo-service/demo-service:v0.0.0-x
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8083
          volumeMounts:
            - name: demo-cm
              mountPath: /config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
