apiVersion: v1
kind: Service
metadata:
  name: demo
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|demo'
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
